CREATE DATABASE UBD
USER SYS IDENTIFIED BY sys_password 
USER SYSTEM IDENTIFIED BY system_password 
LOGFILE 
GROUP 1 ('D:\Aplicatii\oradata\UBD\REDO01.rdo') SIZE 100M, 
GROUP 2 ('D:\Aplicatii\oradata\UBD\REDO02.rdo') SIZE 100M, 
GROUP 3 ('D:\Aplicatii\oradata\UBD\REDO03.rdo') SIZE 100M 
DATAFILE 'D:\Aplicatii\oradata\UBD\SYSTEM01.dbf' SIZE 325M REUSE 
SYSAUX DATAFILE 'D:\Aplicatii\oradata\UBD\SYSAUX01.dbf' SIZE 325M REUSE 
MAXLOGFILES 32 
MAXLOGMEMBERS 5 
MAXLOGHISTORY 1 
MAXDATAFILES 100 
CHARACTER SET US7ASCII 
NATIONAL CHARACTER SET AL16UTF16 
EXTENT MANAGEMENT LOCAL 
DEFAULT TABLESPACE users 
DATAFILE 'D:\Aplicatii\oradata\UBD\USERS01.dbf' SIZE 500M REUSE AUTOEXTEND ON 
MAXSIZE UNLIMITED 
DEFAULT TEMPORARY TABLESPACE temp 
TEMPFILE 'D:\Aplicatii\oradata\UBD\TEMP01.dbf' SIZE 20M REUSE 
UNDO TABLESPACE undotbs1 
DATAFILE 'D:\Aplicatii\oradata\UBD\UNDOTBS01.dbf' SIZE 200M REUSE AUTOEXTEND 
ON MAXSIZE UNLIMITED
/